# Generated by Django 4.2.7 on 2025-11-24 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_plano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plano',
            old_name='benefiios',
            new_name='beneficios',
        ),
    ]
