# Generated by Django 4.2.7 on 2025-11-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_benefiios_plano_beneficios'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descricao',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
